name: REQ)Content-Editor

on:
  push:
    branches: [ scalable ]
  pull_request:
    branches: [ scalable ]
    
jobs:

          
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
#    needs: test
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
      REGION: europe-west3
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: dev-cluster
      GKE_ZONE: europe-central2-b
      DEPLOYMENT_NAME: content-editor-develop # TODO: update deployment name if changed in deployment.yaml
      
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true    

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
        
      - name: GIT checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME
      - name: Push Docker image
        run: docker push $IMAGE_NAME    
        
      - run: |-
         gcloud container clusters get-credentials "$GKE_CLUSTER" --zone="$GKE_ZONE" --project="$PROJECT_ID"
      
      - name: Deploy
        run: |-
          kubectl apply -f deployment.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
